In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter('ignore')

In [2]:
df = pd.read_csv('Movies_Metadata.csv')
df.head()

Title  Year  Rating  \
0                                      Blood & Money  2023     0.0   
1  An Oprah Winfrey Special: The Menopause Revolu...  2025     5.7   
2                                Brothers from Malta  2022     6.0   
3                                    Frozen Hot Boys  2025     0.0   
4                                                G20  2025     0.0   

   Runtime (min)                Genres Language   IMDb Code  Summary  \
0             93                 Drama       en  tt30957598      NaN   
1              0                Action       en  tt36404383      NaN   
2              0                Comedy       en  tt10805280      NaN   
3            117  Comedy, Drama, Sport       th  tt35669015      NaN   
4            108      Action, Thriller       en  tt23476986      NaN   

                                                 URL  
0             https://yts.mx/movies/blood-money-2023  
1  https://yts.mx/movies/an-oprah-winfrey-special...  
2     https://yts.mx/movies/brothers-from-malta-2022  
3         https://yts.mx/movies/frozen-hot-boys-2025  
4                     https://yts.mx/movies/g20-2025

In [3]:
df.shape

(4900, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4900 entries, 0 to 4899
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Title          4900 non-null   object 
 1   Year           4900 non-null   int64  
 2   Rating         4900 non-null   float64
 3   Runtime (min)  4900 non-null   int64  
 4   Genres         4892 non-null   object 
 5   Language       4887 non-null   object 
 6   IMDb Code      4900 non-null   object 
 7   Summary        0 non-null      float64
 8   URL            4900 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 344.7+ KB


In [5]:
df.columns.tolist()

['Title',
 'Year',
 'Rating',
 'Runtime (min)',
 'Genres',
 'Language',
 'IMDb Code',
 'Summary',
 'URL']

In [6]:
df.isnull().sum()

Title               0
Year                0
Rating              0
Runtime (min)       0
Genres              8
Language           13
IMDb Code           0
Summary          4900
URL                 0
dtype: int64

In [7]:
df['Title'].unique()

array(['Blood & Money',
       'An Oprah Winfrey Special: The Menopause Revolution',
       'Brothers from Malta', ..., 'Mr. Right',
       "Gabriel's Redemption: Part Three",
       'Puffin Rock and the New Friends'], dtype=object)

In [8]:
df['Title'].nunique()

4830

In [9]:
df['Year'].unique()

array([2023, 2025, 2022, 1934, 1933, 2024, 2019, 2015, 2008, 1941, 2011,
       2021, 2013, 1977, 2020, 2003, 2012, 2018, 2016, 1994, 2017, 2009,
       2014, 2005, 2006, 1992, 1990, 1955, 2007, 1981, 2001, 1939, 1991,
       1996, 1954, 2004, 1949, 1999, 1979, 1974, 1995, 1985, 1963, 2010,
       1989, 1993, 1961, 1984, 1968, 1944, 1921, 1982, 1997, 1928, 2000,
       1998, 1927, 1975, 1978, 1969, 2002, 1964, 1960, 1971, 1967, 1938,
       1965, 1972, 1988, 1959, 1953, 1966, 1970, 1980, 1952, 1986, 1973,
       1957, 1922, 1987, 1983, 1932, 1935, 1956, 1912, 1958, 1940, 1950,
       1948, 1946, 1976, 1945, 1926, 1930, 1947, 1929, 1920, 1951, 1931,
       1936, 1937, 1943, 1942, 1925, 1962, 1915], dtype=int64)

In [10]:
df['Rating'].unique()

array([0. , 5.7, 6. , 7.4, 6.4, 6.9, 7.7, 7.5, 8.2, 8.1, 7.3, 5.4, 3.5,
       7.8, 6.3, 5.1, 8. , 3.4, 4.8, 7.6, 7.2, 7.1, 6.5, 6.7, 7. , 1.1,
       6.1, 4.2, 5. , 4.6, 2.1, 4.3, 5.9, 4.5, 5.3, 6.2, 3.7, 6.8, 5.5,
       6.6, 8.5, 3.8, 5.8, 4.7, 3.6, 5.2, 7.9, 5.6, 2.4, 2.6, 3.3, 4. ,
       4.4, 4.9, 2.7, 3. , 3.2, 2. , 9. , 1.9, 8.3, 2.5, 4.1, 2.2, 3.9,
       8.8, 2.8, 8.6, 9.2, 2.9, 8.4, 8.7, 8.9, 2.3, 3.1, 9.1, 1.3, 9.3,
       9.6, 1.8, 1.6, 9.4, 1.7, 1.4])

In [11]:
df[df['Rating'] == 0]['Year'].value_counts()

Year
2023    19
2024    19
2025    16
2019     5
2021     4
2020     4
2022     4
2017     2
2007     1
2018     1
2015     1
1980     1
2011     1
2009     1
1993     1
Name: count, dtype: int64

In [12]:
df['Runtime (min)'].unique()

array([ 93,   0, 117, 108,  91, 118,  86, 131,  90,  84, 133, 148,  88,
        61,  58,  87,  62,  24,  63,  73,  83, 145, 105,  75,  76, 132,
        45, 103,  44,  67,  60, 100, 107,  77,  85,  96,  57, 136, 114,
        89, 123, 102,  97, 110, 116, 120, 101,  41, 126, 104, 111, 113,
       129, 109,  99,  94, 106,  39, 137,  80,  70, 150, 135, 124,  72,
        78, 122, 121, 119,  54,  65, 115,  81,  98,  22,  92,  71,   7,
        79,  17,  42,  74,  95,  69, 151,  46,  66, 142,  82, 156, 125,
        59, 130, 134, 158, 163, 191, 180, 160, 157,  56,  53,  11, 112,
       168,  49, 155, 141,  30,  40, 147,  13, 128, 146, 174, 169, 140,
        28, 138,  68,  55, 240,  29, 439,  34, 127,  38,  47, 223, 152,
       154,  12,  52, 139,  50,  18, 176,  48, 324,  23,  26,  51,  64,
       198, 192, 216, 167, 143, 166, 224, 360, 165, 159,   5, 201, 144,
        20, 170,  25, 149, 164, 268, 282, 225, 153, 173, 306,   6, 219,
       193, 220,  36, 178, 177, 295, 185, 188, 183,  15,   4, 16

In [13]:
df['Genres'].unique()

array(['Drama', 'Action', 'Comedy', 'Comedy, Drama, Sport',
       'Action, Thriller', 'Drama, Romance', 'Drama, Fantasy, Romance',
       'Drama, Thriller', 'Documentary', 'Drama, Horror, Mystery',
       'Comedy, Crime, Mystery, Romance', 'Music', 'Family',
       'Crime, Drama, Horror, Mystery',
       'Adventure, Animation, Comedy, Family, Fantasy',
       'Adventure, Animation, Family', 'Animation', 'Comedy, Drama',
       'Biography, Drama', 'Documentary, Music',
       'Adventure, Animation, Drama, Family', 'Crime', 'Romance',
       'Comedy, Horror, Sci-Fi', 'Action, Fantasy, Horror', 'Horror',
       'Drama, Horror, Mystery, Thriller', 'Animation, Family', 'Western',
       'Comedy, Horror', 'Sci-Fi', 'Thriller', 'Action, Comedy, Thriller',
       'Drama, Fantasy, Thriller',
       'Adventure, Animation, Comedy, Family, Musical, Western',
       'Action, Drama', 'Drama, Sci-Fi', 'Biography, Documentary, Music',
       'Documentary, History', 'Comedy, Crime, Drama',
       'Com

In [14]:
df['Genres'].nunique()

778

In [15]:
df['Language'].unique()

array(['en', 'th', 'ko', 'te', 'pa', 'es', 'de', 'fr', 'ta', 'he', 'pt',
       'cn', 'nl', 'sv', 'id', 'zh', 'ja', 'dz', nan, 'it', 'fi', 'tl',
       'ms', 'fa', 'ml', 'ru', 'et', 'ar', 'kn', 'hi', 'no', 'fy', 'tr',
       'cs', 'da', 'ur', 'ca', 'hu', 'ro', 'vi', 'is', 'mo', 'bo', 'pl',
       'sk', 'bg', 'sq', 'mr', 'sh', 'ig', 'zu', 'hr', 'el', 'mk', 'sr',
       'uk', 'kk', 'lv', 'se', 'bn', 'ff', 'bs', 'yi', 'jv', 'ne', 'ka',
       'ku', 'uz', 'af', 'gu', 'ga', 'gl', 'sl'], dtype=object)

In [16]:
df['Language'].nunique()

72

In [17]:
df['IMDb Code'].nunique()

4869

In [18]:
df['Summary'].nunique()

0

In [19]:
df['URL'].nunique()

4869

In [20]:
df.duplicated().sum() #Cheking duplicates

31

### Data Cleaning

In [21]:
df = df[df['Rating'] > 0]

In [22]:
df = df[df['Runtime (min)'] > 0]

In [23]:
df.drop(columns = ['Summary'],inplace = True)

In [24]:
df = df.rename(columns = {'Runtime (min)': 'Runtime'})

In [25]:
df.drop_duplicates(inplace = True,ignore_index = True)

In [26]:
df['Genres'].fillna('Unknown', inplace=True)

In [27]:
df['Language'].fillna('Language', inplace=True)

In [28]:
df

Title  Year  Rating  Runtime  \
0                                        Morningside  2025     7.4       91   
1                                        Honey Sweet  2023     6.4      118   
2                                        Sadie McKee  1934     6.9       93   
3                       Gabriel Over the White House  1933     6.4       86   
4                             The Paradise of Thorns  2024     7.7      131   
...                                              ...   ...     ...      ...   
4581                                    Broken Lance  2024     5.5       29   
4582  The Girl Locked Upstairs: The Tanya Kach Story  2024     5.9       88   
4583                                       Mr. Right  2023     5.9       95   
4584                Gabriel's Redemption: Part Three  2023     6.1       96   
4585                 Puffin Rock and the New Friends  2023     6.6       80   

                                            Genres Language   IMDb Code  \
0                                            Drama       en  tt24666718   
1                                           Comedy       ko  tt28625660   
2                                   Drama, Romance       en   tt0025740   
3                          Drama, Fantasy, Romance       en   tt0024044   
4                                  Drama, Thriller       th  tt32362515   
...                                            ...      ...         ...   
4581                             Action, Animation       en  tt31720896   
4582                          Action, Crime, Drama       en  tt32559891   
4583                               Action, Romance       en  tt28639015   
4584                               Action, Romance       en  tt27845943   
4585  Action, Adventure, Animation, Comedy, Family       en  tt26700853   

                                                    URL  
0                https://yts.mx/movies/morningside-2025  
1                https://yts.mx/movies/honey-sweet-2023  
2                https://yts.mx/movies/sadie-mckee-1934  
3     https://yts.mx/movies/gabriel-over-the-white-h...  
4     https://yts.mx/movies/the-paradise-of-thorns-2024  
...                                                 ...  
4581            https://yts.mx/movies/broken-lance-2024  
4582  https://yts.mx/movies/the-girl-locked-upstairs...  
4583                https://yts.mx/movies/mr-right-2023  
4584  https://yts.mx/movies/gabriels-redemption-part...  
4585  https://yts.mx/movies/puffin-rock-and-the-new-...  

[4586 rows x 8 columns]

### Modeling

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
df1 = vect.fit_transform(df['Genres'])
df1 = df1.toarray()

In [30]:
df2 = vect.fit_transform(df['Language'])
df2 = df2.toarray()

In [31]:
df_total = np.concatenate([df1,df2],axis = 1)

In [32]:
df_total

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.64735542, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.64735542, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.33200485, 0.47480469, 0.57624671, ..., 0.        , 0.        ,
        0.        ]])

- **Cosine Similerity**

In [33]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(df_total)
print(similarity)

[[1.         0.         0.76813138 ... 0.5        0.5        0.5       ]
 [0.         1.         0.         ... 0.         0.         0.15168249]
 [0.76813138 0.         1.         ... 0.82166292 0.82166292 0.5       ]
 ...
 [0.5        0.         0.82166292 ... 1.         1.         0.60746257]
 [0.5        0.         0.82166292 ... 1.         1.         0.60746257]
 [0.5        0.15168249 0.5        ... 0.60746257 0.60746257 1.        ]]


In [34]:
similarity.shape

(4586, 4586)

- **Creating a list**

In [35]:
list_of_titles = df['Title'].tolist()

In [36]:
#getting movie name from the user
movie_search = input('Enter a movie name you want :' )

Enter a movie name you want : Honey Sweet


In [37]:
import difflib
find_close_match = difflib.get_close_matches(movie_search,list_of_titles)
print(find_close_match)

['Honey Sweet', 'HoneyBee', 'Home Sweet Loan']


In [38]:
close_match = find_close_match[0]
print(close_match)

Honey Sweet


In [39]:
index_of_item = df[df['Title'] == close_match].index.tolist()[0]
index_of_item

1

In [40]:
similarity_score = list(enumerate(similarity[index_of_item]))
print(similarity_score)

[(0, 0.0), (1, 0.9999999999999998), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.4999999999999999), (6, 0.0), (7, 0.4999999999999999), (8, 0.4999999999999999), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.18563618912231902), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.14100590760456105), (18, 0.0), (19, 0.0), (20, 0.4999999999999999), (21, 0.38688661130829566), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.1733801978372286), (30, 0.0), (31, 0.14100590760456105), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.30565352039237503), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.26761445187478167), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.11344506583490996), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.38688661130829566), (50, 0.0), (51, 0.0), (52, 0.4999999999999999), (53, 0.26761445187478167), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.25922489046825764), (58, 0.27397546206455553), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (6

In [41]:
a = []
for i in similarity_score:
    if (i[1] >= 0.75):
        a.append(i[0])

In [42]:
a

[1, 127, 144, 247, 3757, 3964, 4325]

In [43]:
df3 = pd.DataFrame({})
for movie in a:
    df3[movie] = df.iloc[movie][['Title','Year','Rating','Runtime','Genres','Language','IMDb Code','URL']]

In [44]:
df3.T

Title  Year Rating Runtime                    Genres Language  \
1        Honey Sweet  2023    6.4     118                    Comedy       ko   
127   Enemies In-Law  2015    5.9     119            Action, Comedy       ko   
144              4PM  2024    5.9     111   Comedy, Drama, Thriller       ko   
247     About Family  2024    6.8     106                    Comedy       ko   
3757      New Normal  2022    6.2     112  Comedy, Horror, Thriller       ko   
3964           Pilot  2024    6.2     110                    Comedy       ko   
4325   Brave Citizen  2023    6.5     112     Action, Comedy, Drama       ko   

       IMDb Code                                        URL  
1     tt28625660     https://yts.mx/movies/honey-sweet-2023  
127    tt5449088  https://yts.mx/movies/enemies-in-law-2015  
144   tt25383302             https://yts.mx/movies/4pm-2024  
247   tt26224870    https://yts.mx/movies/about-family-2024  
3757  tt21983200      https://yts.mx/movies/new-normal-2022  
3964  tt32175399           https://yts.mx/movies/pilot-2024  
4325  tt22505214   https://yts.mx/movies/brave-citizen-2023